
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  homerico:
    image: elixir:1.13
    container_name: avb-app-sx-homerico
    build: ./homerico
    command: bash -c "(mix local.rebar --force) && (mix do compile --force) && mix phx.server"
    env_file:
      - .env
      - ./homerico/.env
    volumes:
      - ./homerico/:/usr/app/
      - /usr/app/_build/
    expose:
      - ${HOMERICO_SERVICE_PORT}
    restart: 'no'

##########################################################################################################################
