
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  db:
    image: mysql:8
    container_name: db-avb
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    restart: always

##########################################################################################################################

  homerico:
    image: node:16
    container_name: cx-homerico
    build: ./services/homerico
    command: bash -c "yarn && yarn build && yarn nonstop"
    env_file: .env
    volumes:
      # Folders
      - ./services/homerico/src/:/usr/app/src/
      - ./services/homerico/node_modules/:/usr/app/node_modules/
      # Files
      - ./services/homerico/yarn.lock:/usr/app/yarn.lock
      - ./services/homerico/package.json:/usr/app/package.json
      - ./services/homerico/tsconfig.json:/usr/app/tsconfig.json
    expose:
      - ${HOMERICO_NETWORK_PORT}
    restart: always

##########################################################################################################################

  app:
    image: python:3.10
    container_name: avb-app
    build: ./app
    command: bash -c "pip install -r requirements.txt && cd .. && python -m app"
    env_file: .env
    volumes:
      - ./app/:/usr/app/
      - /usr/local/lib/python3.10/site-packages/
    ports:
      - "${AVB_APP_PORT}:${AVB_APP_PORT}"
    depends_on:
      - db
      - homerico
    restart: always

##########################################################################################################################
