
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  db:
    image: mysql:8
    container_name: db-avb
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    restart: always

##########################################################################################################################

  homerico:
    image: node:16
    container_name: cx-homerico
    build: ./services/homerico
    command: bash -c "yarn && yarn build && yarn nonstop"
    env_file:
      - .env
      - ./services/homerico/.env
    volumes:
      - ./services/homerico/:/usr/app/
      - /usr/app/build/
    expose:
      - ${HOMERICO_NETWORK_PORT}
    restart: always

##########################################################################################################################

  mysql:
    image: python:3.10
    container_name: cx-mysql
    build: ./services/mysql
    command: bash -c "pip install -r requirements.txt && cd .. && python -m app"
    env_file:
      - .env
      - ./services/mysql/.env
    volumes:
      - ./services/mysql/:/usr/app/
    expose:
      - ${MYSQL_NETWORK_PORT}
    restart: always

##########################################################################################################################

  odbc:
    image: python:3.10
    container_name: cx-odbc
    build: ./services/odbc
    command: bash -c "pip install -r requirements.txt && cd .. && python -m app"
    env_file:
      - .env
      - ./services/odbc/.env
    volumes:
      - ./services/odbc/:/usr/app/
    expose:
      - ${ODBC_NETWORK_PORT}
    restart: always

##########################################################################################################################

  oracle:
    image: python:3.10
    container_name: cx-oracle
    build: ./services/oracle
    command: bash -c "pip install -r requirements.txt && cd .. && python -m app"
    env_file:
      - .env
      - ./services/oracle/.env
    volumes:
      - ./services/oracle/:/usr/app/
    expose:
      - ${ORACLE_NETWORK_PORT}
    restart: always

##########################################################################################################################

  app:
    image: python:3.10
    container_name: avb-app
    build: ./app
    command: bash -c "pip install -r requirements.txt && cd .. && python -m app"
    env_file: .env
    volumes:
      - ./app/:/usr/app/
    ports:
      - "${AVB_APP_PORT}:${AVB_APP_PORT}"
    depends_on:
      - db
      - homerico
      - mysql
      - odbc
      - oracle
    restart: always

##########################################################################################################################
