
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  client:
    image: mellon-yellow/python-3.10-avb-app-client-api
    container_name: avb-app-client-api
    build: ./client
    command: bash -c "./setup.sh"
    env_file: .env
    volumes:
      - ./app/:/usr/app/
    ports:
      - "${AVB_APP_PORT}:${AVB_APP_PORT}"
    depends_on:
      - db
      - homerico
      - mysql
      - odbc
      - opc
      - oracle
    restart: always

##########################################################################################################################

  homerico:
    image: mellon-yellow/elixir-1.13-avb-app-client-homerico
    container_name: avb-app-client-homerico
    build: ./homerico
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./homerico/.env
    volumes:
      - ./homerico/:/usr/app/
    expose:
      - ${HOMERICO_SERVICE_PORT}
    restart: always

##########################################################################################################################

  mysql:
    image: mellon-yellow/python-3.10-avb-app-client-mysql
    container_name: avb-app-client-mysql
    build: ./mysql
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./mysql/.env
    volumes:
      - ./mysql/:/usr/app/
    expose:
      - ${MYSQL_SERVICE_PORT}
    restart: always

##########################################################################################################################

  odbc:
    image: mellon-yellow/python-3.10-avb-app-client-odbc
    container_name: avb-app-client-odbc
    build: ./odbc
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./odbc/.env
    volumes:
      - ./odbc/:/usr/app/
    expose:
      - ${ODBC_SERVICE_PORT}
    restart: always

#########################################################################################################################

  opc:
    image: melon-yellow/elixir-1.13-avb-app-client-opc
    container_name: avb-app-client-opc
    build: ./opc
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./opc/.env
    volumes:
      - ./opc/:/usr/app/
    ports:
      - '${OPC_SERVICE_PORT}:${OPC_SERVICE_PORT}'
    restart: always

##########################################################################################################################

  oracle:
    image: mellon-yellow/python-3.10-avb-app-client-oracle
    container_name: avb-app-client-oracle
    build: ./oracle
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./oracle/.env
    volumes:
      - ./oracle/:/usr/app/
    expose:
      - ${ORACLE_SERVICE_PORT}
    restart: always

##########################################################################################################################
