
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  client:
    image: melon-yellow/python-3.10-${CLIENT_SERVICE_NAME}
    container_name: ${CLIENT_SERVICE_NAME}
    build: ./client
    command: bash -c "./setup.sh"
    env_file: .env
    volumes:
      - ./app/:/usr/app/
    ports:
      - "${AVB_APP_PORT}:${AVB_APP_PORT}"
    depends_on:
      - db
      - homerico
      - mysql
      - odbc
      - opc
      - oracle
    restart: always

##########################################################################################################################

  homerico:
    image: melon-yellow/elixir-1.13-${HOMERICO_SERVICE_NAME}
    container_name: ${HOMERICO_SERVICE_NAME}
    build: ./homerico
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./homerico/.env
    volumes:
      - ./homerico/:/usr/app/
    expose:
      - ${HOMERICO_SERVICE_PORT}
    restart: always

##########################################################################################################################

  mysql:
    image: melon-yellow/python-3.10-${MYSQL_SERVICE_NAME}
    container_name: ${MYSQL_SERVICE_NAME}
    build: ./mysql
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./mysql/.env
    volumes:
      - ./mysql/:/usr/app/
    expose:
      - ${MYSQL_SERVICE_PORT}
    restart: always

##########################################################################################################################

  odbc:
    image: melon-yellow/python-3.10-${ODBC_SERVICE_NAME}
    container_name: ${ODBC_SERVICE_NAME}
    build: ./odbc
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./odbc/.env
    volumes:
      - ./odbc/:/usr/app/
    expose:
      - ${ODBC_SERVICE_PORT}
    restart: always

#########################################################################################################################

  opc:
    image: melon-yellow/elixir-1.13-${OPC_SERVICE_NAME}
    container_name: ${OPC_SERVICE_NAME}
    build: ./opc
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./opc/.env
    volumes:
      - ./opc/:/usr/app/
    expose:
      - ${OPC_SERVICE_PORT}
    restart: always

##########################################################################################################################

  oracle:
    image: melon-yellow/python-3.10-${ORACLE_SERVICE_NAME}
    container_name: ${ORACLE_SERVICE_NAME}
    build: ./oracle
    command: bash -c "./setup.sh"
    env_file:
      - .env
      - ./oracle/.env
    volumes:
      - ./oracle/:/usr/app/
    expose:
      - ${ORACLE_SERVICE_PORT}
    restart: always

##########################################################################################################################
