[package]
name = "io_config"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "io_config"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
gio = "0.15.1"
glib = "0.15.1"